# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# BudgetQuestion
10.times do
  Entities::BudgetQuestion.create
end

# GoalType
Entities::GoalType.create(id:1, name: '住宅購入/頭金', img_url: "/goal_types/1/bg-card-goal-house.png")
Entities::GoalType.create(id:2, name: '子供教育資金', img_url: "/goal_types/2/bg-card-goal-education.png")
Entities::GoalType.create(id:3, name: '結婚/旅行', img_url: "/goal_types/3/bg-card-goal-married.png")
Entities::GoalType.create(id:4, name: 'とりあえず貯金', img_url: "/goal_types/4/bg-card-goal-savings.png")
Entities::GoalType.create(id:5, name: '老後資金', img_url: "/goal_types/5/bg-card-goal-pension.png")
Entities::GoalType.create(id:6, name: '繰り上げ返済', img_url: "/goal_types/6/bg-card-goal-repayment.png")
Entities::GoalType.create(id:7, name: '車/バイク', img_url: "/goal_types/7/bg-card-goal-car.png")
Entities::GoalType.create(id:8, name: 'その他', img_url: "/goal_types/8/bg-card-goal-uncategory.png")

# at_groupted_category
Entities::AtGroupedCategory.create(id:1 , category_type: 'expense', order_key: 19, version:1, category_name: '未分類')
Entities::AtGroupedCategory.create(id:2 , category_type: 'expense', order_key: 1 , version:1, category_name: '食費')
Entities::AtGroupedCategory.create(id:3 , category_type: 'expense', order_key: 8 , version:1, category_name: '交際')
Entities::AtGroupedCategory.create(id:4 , category_type: 'expense', order_key: 2 , version:1, category_name: '日用品')
Entities::AtGroupedCategory.create(id:5 , category_type: 'expense', order_key: 10, version:1, category_name: '医療')
Entities::AtGroupedCategory.create(id:6 , category_type: 'expense', order_key: 4 , version:1, category_name: '趣味・娯楽')
Entities::AtGroupedCategory.create(id:7 , category_type: 'expense', order_key: 3 , version:1, category_name: '交通')
Entities::AtGroupedCategory.create(id:8 , category_type: 'expense', order_key: 11, version:1, category_name: '教育')
Entities::AtGroupedCategory.create(id:9 , category_type: 'expense', order_key: 5 , version:1, category_name: '住宅・オフィス')
Entities::AtGroupedCategory.create(id:10, category_type: 'expense', order_key: 7 , version:1, category_name: '通信費・送料')
Entities::AtGroupedCategory.create(id:11, category_type: 'expense', order_key: 14, version:1, category_name: '車')
Entities::AtGroupedCategory.create(id:12, category_type: 'expense', order_key: 12, version:1, category_name: '年金・保険料')
Entities::AtGroupedCategory.create(id:13, category_type: 'expense', order_key: 6 , version:1, category_name: '水道光熱')
Entities::AtGroupedCategory.create(id:14, category_type: 'expense', order_key: 13, version:1, category_name: '税金')
Entities::AtGroupedCategory.create(id:15, category_type: 'expense', order_key: 15, version:1, category_name: '投資')
Entities::AtGroupedCategory.create(id:16, category_type: 'expense', order_key: 16, version:1, category_name: '返済')
Entities::AtGroupedCategory.create(id:17, category_type: 'income' , order_key: 17, version:1, category_name: '入金')
Entities::AtGroupedCategory.create(id:18, category_type: 'expense', order_key: 9 , version:1, category_name: '出金')
Entities::AtGroupedCategory.create(id:19, category_type: 'expense', order_key: 18, version:1, category_name: '手数料')
Entities::AtGroupedCategory.create(id:20, category_type: 'expense', order_key: 1 , version:2, category_name: '食費')
Entities::AtGroupedCategory.create(id:21, category_type: 'expense', order_key: 2 , version:2, category_name: '日用品')
Entities::AtGroupedCategory.create(id:22, category_type: 'expense', order_key: 3 , version:2, category_name: '交通費')
Entities::AtGroupedCategory.create(id:23, category_type: 'expense', order_key: 4 , version:2, category_name: '趣味・娯楽')
Entities::AtGroupedCategory.create(id:24, category_type: 'expense', order_key: 5 , version:2, category_name: '衣服・美容')
Entities::AtGroupedCategory.create(id:25, category_type: 'expense', order_key: 6 , version:2, category_name: '健康・医療')
Entities::AtGroupedCategory.create(id:26, category_type: 'expense', order_key: 7 , version:2, category_name: '健康・医療')
Entities::AtGroupedCategory.create(id:27, category_type: 'expense', order_key: 8 , version:2, category_name: '教育・教養')
Entities::AtGroupedCategory.create(id:28, category_type: 'expense', order_key: 9 , version:2, category_name: '現金・カード')
Entities::AtGroupedCategory.create(id:29, category_type: 'expense', order_key: 10, version:2, category_name: '水道・光熱費')
Entities::AtGroupedCategory.create(id:30, category_type: 'expense', order_key: 11, version:2, category_name: '通信費')
Entities::AtGroupedCategory.create(id:31, category_type: 'expense', order_key: 12, version:2, category_name: '住宅')
Entities::AtGroupedCategory.create(id:32, category_type: 'expense', order_key: 13, version:2, category_name: '車・バイク')
Entities::AtGroupedCategory.create(id:33, category_type: 'expense', order_key: 14, version:2, category_name: '税・社会保障')
Entities::AtGroupedCategory.create(id:34, category_type: 'expense', order_key: 15, version:2, category_name: '保険')
Entities::AtGroupedCategory.create(id:35, category_type: 'expense', order_key: 16, version:2, category_name: '特別な支出')
Entities::AtGroupedCategory.create(id:36, category_type: 'expense', order_key: 17, version:2, category_name: 'その他')
Entities::AtGroupedCategory.create(id:37, category_type: 'expense', order_key: 18, version:2, category_name: '未分類')
Entities::AtGroupedCategory.create(id:38, category_type: 'income' , order_key: 19, version:2, category_name: '入金')

# at_transaction_category
Entities::AtTransactionCategory.create(id:1  , at_grouped_category_id: 1 , order_key: 149  , at_category_id: '0000' , category_name1: '未分類' , category_name2 '未分類')
Entities::AtTransactionCategory.create(id:2  , at_grouped_category_id: 2 , order_key: 9    , at_category_id: '0181' , category_name1: '食費' , category_name2 '昼食')
Entities::AtTransactionCategory.create(id:3  , at_grouped_category_id: 2 , order_key: 10   , at_category_id: '0182' , category_name1: '食費' , category_name2 '外食')
Entities::AtTransactionCategory.create(id:4  , at_grouped_category_id: 2 , order_key: 11   , at_category_id: '0101' , category_name1: '食費' , category_name2 '和食')
Entities::AtTransactionCategory.create(id:5  , at_grouped_category_id: 2 , order_key: 12   , at_category_id: '0102' , category_name1: '食費' , category_name2 '洋食')
Entities::AtTransactionCategory.create(id:6  , at_grouped_category_id: 2 , order_key: 13   , at_category_id: '0103' , category_name1: '食費' , category_name2 'バイキング')
Entities::AtTransactionCategory.create(id:7  , at_grouped_category_id: 2 , order_key: 14   , at_category_id: '0104' , category_name1: '食費' , category_name2 '中華')
Entities::AtTransactionCategory.create(id:8  , at_grouped_category_id: 2 , order_key: 15   , at_category_id: '0105' , category_name1: '食費' , category_name2 'アジア料理、エスニック')
Entities::AtTransactionCategory.create(id:9  , at_grouped_category_id: 2 , order_key: 16   , at_category_id: '0106' , category_name1: '食費' , category_name2 'ラーメン')
Entities::AtTransactionCategory.create(id:10 , at_grouped_category_id: 2 , order_key: 17   , at_category_id: '0107' , category_name1: '食費' , category_name2 'カレー')
Entities::AtTransactionCategory.create(id:11 , at_grouped_category_id: 2 , order_key: 18   , at_category_id: '0108' , category_name1: '食費' , category_name2 '焼肉、ホルモン、ジンギスカン')
Entities::AtTransactionCategory.create(id:12 , at_grouped_category_id: 2 , order_key: 19   , at_category_id: '0109' , category_name1: '食費' , category_name2 '鍋')
Entities::AtTransactionCategory.create(id:13 , at_grouped_category_id: 2 , order_key: 20   , at_category_id: '0111' , category_name1: '食費' , category_name2 '定食、食堂')
Entities::AtTransactionCategory.create(id:14 , at_grouped_category_id: 2 , order_key: 21   , at_category_id: '0112' , category_name1: '食費' , category_name2 '創作料理、無国籍料理')
Entities::AtTransactionCategory.create(id:15 , at_grouped_category_id: 2 , order_key: 22   , at_category_id: '0113' , category_name1: '食費' , category_name2 '自然食、薬膳、オーガニック')
Entities::AtTransactionCategory.create(id:16 , at_grouped_category_id: 2 , order_key: 6    , at_category_id: '0114' , category_name1: '食費' , category_name2 '持ち帰り、宅配')
Entities::AtTransactionCategory.create(id:17 , at_grouped_category_id: 2 , order_key: 2    , at_category_id: '0115' , category_name1: '食費' , category_name2 'カフェ、喫茶店')
Entities::AtTransactionCategory.create(id:18 , at_grouped_category_id: 2 , order_key: 23   , at_category_id: '0116' , category_name1: '食費' , category_name2 'コーヒー、茶葉専門店')
Entities::AtTransactionCategory.create(id:19 , at_grouped_category_id: 2 , order_key: 3    , at_category_id: '0117' , category_name1: '食費' , category_name2 'パン、サンドイッチ')
Entities::AtTransactionCategory.create(id:20 , at_grouped_category_id: 2 , order_key: 4    , at_category_id: '0118' , category_name1: '食費' , category_name2 'スイーツ')
Entities::AtTransactionCategory.create(id:21 , at_grouped_category_id: 2 , order_key: 24   , at_category_id: '0121' , category_name1: '食費' , category_name2 'ディスコ、クラブハウス')
Entities::AtTransactionCategory.create(id:22 , at_grouped_category_id: 2 , order_key: 5    , at_category_id: '0123' , category_name1: '食費' , category_name2 'ファミレス、ファストフード')
Entities::AtTransactionCategory.create(id:23 , at_grouped_category_id: 2 , order_key: 25   , at_category_id: '0124' , category_name1: '食費' , category_name2 'パーティー、カラオケ')
Entities::AtTransactionCategory.create(id:24 , at_grouped_category_id: 2 , order_key: 26   , at_category_id: '0125' , category_name1: '食費' , category_name2 '屋形船、クルージング')
Entities::AtTransactionCategory.create(id:25 , at_grouped_category_id: 2 , order_key: 27   , at_category_id: '0126' , category_name1: '食費' , category_name2 'テーマパークレストラン')
Entities::AtTransactionCategory.create(id:26 , at_grouped_category_id: 2 , order_key: 28   , at_category_id: '0127' , category_name1: '食費' , category_name2 'オーベルジュ')
Entities::AtTransactionCategory.create(id:27 , at_grouped_category_id: 2 , order_key: 7    , at_category_id: '0128' , category_name1: '食費' , category_name2 'その他')
Entities::AtTransactionCategory.create(id:28 , at_grouped_category_id: 2 , order_key: 1    , at_category_id: '0205' , category_name1: '食費' , category_name2 'コンビニ、スーパー')
Entities::AtTransactionCategory.create(id:29 , at_grouped_category_id: 4 , order_key: 36   , at_category_id: '0203' , category_name1: '日用品' , category_name2 '家電、携帯電話')
Entities::AtTransactionCategory.create(id:30 , at_grouped_category_id: 4 , order_key: 32   , at_category_id: '0209' , category_name1: '日用品' , category_name2 'ファッション、アクセサリー、時計')
Entities::AtTransactionCategory.create(id:31 , at_grouped_category_id: 4 , order_key: 35   , at_category_id: '0208' , category_name1: '日用品' , category_name2 '趣味、スポーツ、工芸')
Entities::AtTransactionCategory.create(id:32 , at_grouped_category_id: 4 , order_key: 29   , at_category_id: '0202' , category_name1: '日用品' , category_name2 'ドラッグストア、市販薬')
Entities::AtTransactionCategory.create(id:33 , at_grouped_category_id: 2 , order_key: 8    , at_category_id: '0210' , category_name1: '食費' , category_name2 '食品、食材')
Entities::AtTransactionCategory.create(id:34 , at_grouped_category_id: 4 , order_key: 31   , at_category_id: '0211' , category_name1: '日用品' , category_name2 '通信販売')
Entities::AtTransactionCategory.create(id:35 , at_grouped_category_id: 4 , order_key: 37   , at_category_id: '0201' , category_name1: '日用品' , category_name2 'メガネ、コンタクトレンズ')
Entities::AtTransactionCategory.create(id:36 , at_grouped_category_id: 4 , order_key: 33   , at_category_id: '0204' , category_name1: '日用品' , category_name2 '百貨店、ショッピングセンター')
Entities::AtTransactionCategory.create(id:37 , at_grouped_category_id: 4 , order_key: 34   , at_category_id: '0206' , category_name1: '日用品' , category_name2 'リサイクル、ディスカウントショップ')
Entities::AtTransactionCategory.create(id:38 , at_grouped_category_id: 4 , order_key: 30   , at_category_id: '0207' , category_name1: '日用品' , category_name2 '生活用品、インテリア')
Entities::AtTransactionCategory.create(id:39 , at_grouped_category_id: 7 , order_key: 38   , at_category_id: '0381' , category_name1: '交通' , category_name2 '電車')
Entities::AtTransactionCategory.create(id:40 , at_grouped_category_id: 7 , order_key: 39   , at_category_id: '0382' , category_name1: '交通' , category_name2 'バス')
Entities::AtTransactionCategory.create(id:41 , at_grouped_category_id: 7 , order_key: 40   , at_category_id: '0383' , category_name1: '交通' , category_name2 'タクシー')
Entities::AtTransactionCategory.create(id:42 , at_grouped_category_id: 7 , order_key: 41   , at_category_id: '0384' , category_name1: '交通' , category_name2 '飛行機')
Entities::AtTransactionCategory.create(id:43 , at_grouped_category_id: 7 , order_key: 42   , at_category_id: '0306' , category_name1: '交通' , category_name2 '交通、レンタカー')
Entities::AtTransactionCategory.create(id:44 , at_grouped_category_id: 7 , order_key: 43   , at_category_id: '0386' , category_name1: '交通' , category_name2 '船')
Entities::AtTransactionCategory.create(id:45 , at_grouped_category_id: 7 , order_key: 44   , at_category_id: '0399' , category_name1: '交通' , category_name2 'その他交通')
Entities::AtTransactionCategory.create(id:46 , at_grouped_category_id: 9 , order_key: 56   , at_category_id: '0409' , category_name1: '住宅・オフィス' , category_name2 '住宅、不動産')
Entities::AtTransactionCategory.create(id:47 , at_grouped_category_id: 9 , order_key: 60   , at_category_id: '0482' , category_name1: '住宅・オフィス' , category_name2 'オフィス用品')
Entities::AtTransactionCategory.create(id:48 , at_grouped_category_id: 9 , order_key: 57   , at_category_id: '0483' , category_name1: '住宅・オフィス' , category_name2 '地震・火災保険')
Entities::AtTransactionCategory.create(id:49 , at_grouped_category_id: 9 , order_key: 58   , at_category_id: '0484' , category_name1: '住宅・オフィス' , category_name2 '設備')
Entities::AtTransactionCategory.create(id:50 , at_grouped_category_id: 9 , order_key: 59   , at_category_id: '0410' , category_name1: '住宅・オフィス' , category_name2 '住宅設備')
Entities::AtTransactionCategory.create(id:51 , at_grouped_category_id: 13, order_key: 61   , at_category_id: '0581' , category_name1: '水道光熱' , category_name2 '電気')
Entities::AtTransactionCategory.create(id:52 , at_grouped_category_id: 13, order_key: 62   , at_category_id: '0582' , category_name1: '水道光熱' , category_name2 '水道')
Entities::AtTransactionCategory.create(id:53 , at_grouped_category_id: 13, order_key: 63   , at_category_id: '0583' , category_name1: '水道光熱' , category_name2 'ガス')
Entities::AtTransactionCategory.create(id:54 , at_grouped_category_id: 13, order_key: 64   , at_category_id: '0599' , category_name1: '水道光熱' , category_name2 'その他水道光熱費')
Entities::AtTransactionCategory.create(id:55 , at_grouped_category_id: 10, order_key: 65   , at_category_id: '0681' , category_name1: '通信費・送料' , category_name2 '携帯電話')
Entities::AtTransactionCategory.create(id:56 , at_grouped_category_id: 10, order_key: 71   , at_category_id: '0682' , category_name1: '通信費・送料' , category_name2 '固定電話')
Entities::AtTransactionCategory.create(id:57 , at_grouped_category_id: 10, order_key: 67   , at_category_id: '0412' , category_name1: '通信費・送料' , category_name2 '生活サービス')
Entities::AtTransactionCategory.create(id:58 , at_grouped_category_id: 10, order_key: 66   , at_category_id: '0684' , category_name1: '通信費・送料' , category_name2 'インターネット')
Entities::AtTransactionCategory.create(id:59 , at_grouped_category_id: 10, order_key: 69   , at_category_id: '0685' , category_name1: '通信費・送料' , category_name2 '放送視聴料')
Entities::AtTransactionCategory.create(id:60 , at_grouped_category_id: 10, order_key: 70   , at_category_id: '0411' , category_name1: '通信費・送料' , category_name2 '郵便局、宅配便')
Entities::AtTransactionCategory.create(id:61 , at_grouped_category_id: 10, order_key: 68   , at_category_id: '0699' , category_name1: '通信費・送料' , category_name2 'その他通信費・送料')
Entities::AtTransactionCategory.create(id:62 , at_grouped_category_id: 3 , order_key: 75   , at_category_id: '0110' , category_name1: '交際' , category_name2 '居酒屋、ビアホール')
Entities::AtTransactionCategory.create(id:63 , at_grouped_category_id: 3 , order_key: 76   , at_category_id: '0119' , category_name1: '交際' , category_name2 'バー')
Entities::AtTransactionCategory.create(id:64 , at_grouped_category_id: 3 , order_key: 77   , at_category_id: '0120' , category_name1: '交際' , category_name2 'パブ、スナック')
Entities::AtTransactionCategory.create(id:65 , at_grouped_category_id: 3 , order_key: 78   , at_category_id: '0122' , category_name1: '交際' , category_name2 'ビアガーデン')
Entities::AtTransactionCategory.create(id:66 , at_grouped_category_id: 3 , order_key: 79   , at_category_id: '0415' , category_name1: '交際' , category_name2 '葬祭、仏壇')
Entities::AtTransactionCategory.create(id:67 , at_grouped_category_id: 3 , order_key: 80   , at_category_id: '0414' , category_name1: '交際' , category_name2 '結婚式場、結婚相談所')
Entities::AtTransactionCategory.create(id:68 , at_grouped_category_id: 3 , order_key: 73   , at_category_id: '0783' , category_name1: '交際' , category_name2 'プレゼント代')
Entities::AtTransactionCategory.create(id:69 , at_grouped_category_id: 3 , order_key: 74   , at_category_id: '0784' , category_name1: '交際' , category_name2 'お土産代')
Entities::AtTransactionCategory.create(id:70 , at_grouped_category_id: 3 , order_key: 72   , at_category_id: '0799' , category_name1: '交際' , category_name2 'その他交際')
Entities::AtTransactionCategory.create(id:71 , at_grouped_category_id: 5 , order_key: 89   , at_category_id: '0401' , category_name1: '医療' , category_name2 '病院、診療所')
Entities::AtTransactionCategory.create(id:72 , at_grouped_category_id: 5 , order_key: 90   , at_category_id: '0402' , category_name1: '医療' , category_name2 '薬局')
Entities::AtTransactionCategory.create(id:73 , at_grouped_category_id: 5 , order_key: 92   , at_category_id: '0301' , category_name1: '医療' , category_name2 'スポーツ')
Entities::AtTransactionCategory.create(id:74 , at_grouped_category_id: 5 , order_key: 91   , at_category_id: '0403' , category_name1: '医療' , category_name2 'マッサージ、整体、治療院')
Entities::AtTransactionCategory.create(id:75 , at_grouped_category_id: 5 , order_key: 93   , at_category_id: '0404' , category_name1: '医療' , category_name2 '介護、福祉')
Entities::AtTransactionCategory.create(id:76 , at_grouped_category_id: 8 , order_key: 101  , at_category_id: '0406' , category_name1: '教育' , category_name2 '学校、大学、専門学校')
Entities::AtTransactionCategory.create(id:77 , at_grouped_category_id: 8 , order_key: 100  , at_category_id: '0407' , category_name1: '教育' , category_name2 '進学塾、予備校、各種学校')
Entities::AtTransactionCategory.create(id:78 , at_grouped_category_id: 8 , order_key: 99   , at_category_id: '0408' , category_name1: '教育' , category_name2 '保育園、幼稚園、育児')
Entities::AtTransactionCategory.create(id:79 , at_grouped_category_id: 8 , order_key: 97   , at_category_id: '0902' , category_name1: '教育' , category_name2 '教科書等')
Entities::AtTransactionCategory.create(id:80 , at_grouped_category_id: 8 , order_key: 94   , at_category_id: '0903' , category_name1: '教育' , category_name2 '書籍')
Entities::AtTransactionCategory.create(id:81 , at_grouped_category_id: 8 , order_key: 95   , at_category_id: '0904' , category_name1: '教育' , category_name2 '新聞・雑誌')
Entities::AtTransactionCategory.create(id:82 , at_grouped_category_id: 8 , order_key: 96   , at_category_id: '0405' , category_name1: '教育' , category_name2 '趣味、習い事')
Entities::AtTransactionCategory.create(id:83 , at_grouped_category_id: 8 , order_key: 102  , at_category_id: '0906' , category_name1: '教育' , category_name2 'セミナー代')
Entities::AtTransactionCategory.create(id:84 , at_grouped_category_id: 8 , order_key: 98   , at_category_id: '0999' , category_name1: '教育' , category_name2 'その他教育')
Entities::AtTransactionCategory.create(id:85 , at_grouped_category_id: 12, order_key: 107  , at_category_id: '0416' , category_name1: '年金・保険料' , category_name2 '銀行、保険、金融')
Entities::AtTransactionCategory.create(id:86 , at_grouped_category_id: 12, order_key: 103  , at_category_id: '1002' , category_name1: '年金・保険料' , category_name2 '生命保険')
Entities::AtTransactionCategory.create(id:87 , at_grouped_category_id: 12, order_key: 104  , at_category_id: '1003' , category_name1: '年金・保険料' , category_name2 '医療保険')
Entities::AtTransactionCategory.create(id:88 , at_grouped_category_id: 12, order_key: 105  , at_category_id: '1084' , category_name1: '年金・保険料' , category_name2 '損害保険')
Entities::AtTransactionCategory.create(id:89 , at_grouped_category_id: 12, order_key: 106  , at_category_id: '1004' , category_name1: '年金・保険料' , category_name2 '年金')
Entities::AtTransactionCategory.create(id:90 , at_grouped_category_id: 12, order_key: 108  , at_category_id: '1099' , category_name1: '年金・保険料' , category_name2 'その他年金・保険')
Entities::AtTransactionCategory.create(id:91 , at_grouped_category_id: 14, order_key: 109  , at_category_id: '1101' , category_name1: '税金' , category_name2 '所得税・住民税')
Entities::AtTransactionCategory.create(id:92 , at_grouped_category_id: 14, order_key: 110  , at_category_id: '1182' , category_name1: '税金' , category_name2 '消費税')
Entities::AtTransactionCategory.create(id:93 , at_grouped_category_id: 14, order_key: 111  , at_category_id: '1102' , category_name1: '税金' , category_name2 '収入印紙代')
Entities::AtTransactionCategory.create(id:94 , at_grouped_category_id: 14, order_key: 112  , at_category_id: '1199' , category_name1: '税金' , category_name2 'その他税金')
Entities::AtTransactionCategory.create(id:95 , at_grouped_category_id: 11, order_key: 113  , at_category_id: '0413' , category_name1: '車' , category_name2 '自動車、バイク')
Entities::AtTransactionCategory.create(id:96 , at_grouped_category_id: 11, order_key: 114  , at_category_id: '1282' , category_name1: '車' , category_name2 '駐車場')
Entities::AtTransactionCategory.create(id:97 , at_grouped_category_id: 11, order_key: 115  , at_category_id: '1283' , category_name1: '車' , category_name2 '自動車保険')
Entities::AtTransactionCategory.create(id:98 , at_grouped_category_id: 11, order_key: 116  , at_category_id: '1284' , category_name1: '車' , category_name2 '道路料金')
Entities::AtTransactionCategory.create(id:99 , at_grouped_category_id: 11, order_key: 117  , at_category_id: '1285' , category_name1: '車' , category_name2 '自動⾞税')
Entities::AtTransactionCategory.create(id:100, at_grouped_category_id: 11, order_key: 118  , at_category_id: '1286' , category_name1: '車' , category_name2 '維持費')
Entities::AtTransactionCategory.create(id:101, at_grouped_category_id: 11, order_key: 119  , at_category_id: '1287' , category_name1: '車' , category_name2 '車検・整備')
Entities::AtTransactionCategory.create(id:102, at_grouped_category_id: 11, order_key: 120  , at_category_id: '1288' , category_name1: '車' , category_name2 '自動車ローン')
Entities::AtTransactionCategory.create(id:103, at_grouped_category_id: 11, order_key: 121  , at_category_id: '1289' , category_name1: '車' , category_name2 '車両')
Entities::AtTransactionCategory.create(id:104, at_grouped_category_id: 11, order_key: 122  , at_category_id: '1299' , category_name1: '車' , category_name2 'その他車')
Entities::AtTransactionCategory.create(id:105, at_grouped_category_id: 6 , order_key: 49   , at_category_id: '0304' , category_name1: '趣味・娯楽' , category_name2 'ホテル、旅館')
Entities::AtTransactionCategory.create(id:106, at_grouped_category_id: 6 , order_key: 50   , at_category_id: '0307' , category_name1: '趣味・娯楽' , category_name2 '旅行サービス')
Entities::AtTransactionCategory.create(id:107, at_grouped_category_id: 6 , order_key: 53   , at_category_id: '0302' , category_name1: '趣味・娯楽' , category_name2 '麻雀、ゲームセンター')
Entities::AtTransactionCategory.create(id:108, at_grouped_category_id: 6 , order_key: 45   , at_category_id: '0303' , category_name1: '趣味・娯楽' , category_name2 'レジャー、趣味')
Entities::AtTransactionCategory.create(id:109, at_grouped_category_id: 6 , order_key: 46   , at_category_id: '0305' , category_name1: '趣味・娯楽' , category_name2 'エンタメ、映画館、美術館')
Entities::AtTransactionCategory.create(id:110, at_grouped_category_id: 6 , order_key: 52   , at_category_id: '0308' , category_name1: '趣味・娯楽' , category_name2 'パチンコ、パチスロ')
Entities::AtTransactionCategory.create(id:111, at_grouped_category_id: 6 , order_key: 48   , at_category_id: '0418' , category_name1: '趣味・娯楽' , category_name2 '銭湯、浴場')
Entities::AtTransactionCategory.create(id:112, at_grouped_category_id: 6 , order_key: 47   , at_category_id: '0419' , category_name1: '趣味・娯楽' , category_name2 '美容、サロン')
Entities::AtTransactionCategory.create(id:113, at_grouped_category_id: 6 , order_key: 51   , at_category_id: '0417' , category_name1: '趣味・娯楽' , category_name2 'ペット、動物病院')
Entities::AtTransactionCategory.create(id:114, at_grouped_category_id: 6 , order_key: 54   , at_category_id: '0423' , category_name1: '趣味・娯楽' , category_name2 '公共サービス、各種団体')
Entities::AtTransactionCategory.create(id:115, at_grouped_category_id: 6 , order_key: 55   , at_category_id: '0424' , category_name1: '趣味・娯楽' , category_name2 '寺院、神社')
Entities::AtTransactionCategory.create(id:116, at_grouped_category_id: 15, order_key: 123  , at_category_id: '1481' , category_name1: '投資' , category_name2 '配当金')
Entities::AtTransactionCategory.create(id:117, at_grouped_category_id: 15, order_key: 124  , at_category_id: '1482' , category_name1: '投資' , category_name2 '株の売却')
Entities::AtTransactionCategory.create(id:118, at_grouped_category_id: 15, order_key: 125  , at_category_id: '1483' , category_name1: '投資' , category_name2 '株の購入')
Entities::AtTransactionCategory.create(id:119, at_grouped_category_id: 15, order_key: 126  , at_category_id: '1499' , category_name1: '投資' , category_name2 'その他投資')
Entities::AtTransactionCategory.create(id:120, at_grouped_category_id: 16, order_key: 127  , at_category_id: '1581' , category_name1: '返済' , category_name2 'カード返済')
Entities::AtTransactionCategory.create(id:121, at_grouped_category_id: 16, order_key: 128  , at_category_id: '1582' , category_name1: '返済' , category_name2 'ローン返済')
Entities::AtTransactionCategory.create(id:122, at_grouped_category_id: 16, order_key: 129  , at_category_id: '1599' , category_name1: '返済' , category_name2 'その他返済')
Entities::AtTransactionCategory.create(id:123, at_grouped_category_id: 17, order_key: 132  , at_category_id: '1681' , category_name1: '入金' , category_name2 'ATM入金')
Entities::AtTransactionCategory.create(id:124, at_grouped_category_id: 17, order_key: 134  , at_category_id: '1682' , category_name1: '入金' , category_name2 '振込入金')
Entities::AtTransactionCategory.create(id:125, at_grouped_category_id: 17, order_key: 135  , at_category_id: '1683' , category_name1: '入金' , category_name2 '清算入金')
Entities::AtTransactionCategory.create(id:126, at_grouped_category_id: 17, order_key: 130  , at_category_id: '1684' , category_name1: '入金' , category_name2 '給与入金')
Entities::AtTransactionCategory.create(id:127, at_grouped_category_id: 17, order_key: 131  , at_category_id: '1685' , category_name1: '入金' , category_name2 '賞与入金')
Entities::AtTransactionCategory.create(id:128, at_grouped_category_id: 17, order_key: 136  , at_category_id: '1686' , category_name1: '入金' , category_name2 '貯金入金')
Entities::AtTransactionCategory.create(id:129, at_grouped_category_id: 17, order_key: 137  , at_category_id: '1687' , category_name1: '入金' , category_name2 '配当等収入')
Entities::AtTransactionCategory.create(id:130, at_grouped_category_id: 17, order_key: 138  , at_category_id: '1688' , category_name1: '入金' , category_name2 '雑収入')
Entities::AtTransactionCategory.create(id:131, at_grouped_category_id: 17, order_key: 139  , at_category_id: '1689' , category_name1: '入金' , category_name2 '融資入金')
Entities::AtTransactionCategory.create(id:132, at_grouped_category_id: 17, order_key: 140  , at_category_id: '1690' , category_name1: '入金' , category_name2 '家賃所得')
Entities::AtTransactionCategory.create(id:133, at_grouped_category_id: 17, order_key: 141  , at_category_id: '1691' , category_name1: '入金' , category_name2 '利子所得')
Entities::AtTransactionCategory.create(id:134, at_grouped_category_id: 17, order_key: 142  , at_category_id: '1692' , category_name1: '入金' , category_name2 '振込手数料入金')
Entities::AtTransactionCategory.create(id:135, at_grouped_category_id: 17, order_key: 133  , at_category_id: '1699' , category_name1: '入金' , category_name2 'その他入金')
Entities::AtTransactionCategory.create(id:136, at_grouped_category_id: 18, order_key: 81   , at_category_id: '1781' , category_name1: '出金' , category_name2 'ATM出金')
Entities::AtTransactionCategory.create(id:137, at_grouped_category_id: 18, order_key: 82   , at_category_id: '1782' , category_name1: '出金' , category_name2 '雑支出')
Entities::AtTransactionCategory.create(id:138, at_grouped_category_id: 18, order_key: 83   , at_category_id: '1783' , category_name1: '出金' , category_name2 '預金支出')
Entities::AtTransactionCategory.create(id:139, at_grouped_category_id: 18, order_key: 84   , at_category_id: '1784' , category_name1: '出金' , category_name2 '寄付金')
Entities::AtTransactionCategory.create(id:140, at_grouped_category_id: 18, order_key: 85   , at_category_id: '1785' , category_name1: '出金' , category_name2 '会費')
Entities::AtTransactionCategory.create(id:141, at_grouped_category_id: 18, order_key: 86   , at_category_id: '1786' , category_name1: '出金' , category_name2 '定期預金')
Entities::AtTransactionCategory.create(id:142, at_grouped_category_id: 18, order_key: 87   , at_category_id: '1787' , category_name1: '出金' , category_name2 '給与支払')
Entities::AtTransactionCategory.create(id:143, at_grouped_category_id: 18, order_key: 88   , at_category_id: '1799' , category_name1: '出金' , category_name2 'その他出金')
Entities::AtTransactionCategory.create(id:144, at_grouped_category_id: 19, order_key: 143  , at_category_id: '1881' , category_name1: '手数料' , category_name2 '利息')
Entities::AtTransactionCategory.create(id:145, at_grouped_category_id: 19, order_key: 144  , at_category_id: '1882' , category_name1: '手数料' , category_name2 '振込手数料')
Entities::AtTransactionCategory.create(id:146, at_grouped_category_id: 19, order_key: 145  , at_category_id: '1883' , category_name1: '手数料' , category_name2 '振替手数料')
Entities::AtTransactionCategory.create(id:147, at_grouped_category_id: 19, order_key: 146  , at_category_id: '1884' , category_name1: '手数料' , category_name2 '銀行手数料')
Entities::AtTransactionCategory.create(id:148, at_grouped_category_id: 19, order_key: 147  , at_category_id: '1885' , category_name1: '手数料' , category_name2 'ATM手数料')
Entities::AtTransactionCategory.create(id:149, at_grouped_category_id: 19, order_key: 148  , at_category_id: '1899' , category_name1: '手数料' , category_name2 'その他手数料')
Entities::AtTransactionCategory.create(id:150, at_grouped_category_id: 1 , order_key: 150  , at_category_id: '0420' , category_name1: '未分類' , category_name2 '専門職、弁護士、司法書士')
Entities::AtTransactionCategory.create(id:151, at_grouped_category_id: 1 , order_key: 151  , at_category_id: '0421' , category_name1: '未分類' , category_name2 '人材派遣')
Entities::AtTransactionCategory.create(id:152, at_grouped_category_id: 1 , order_key: 152  , at_category_id: '0422' , category_name1: '未分類' , category_name2 '官公庁')
Entities::AtTransactionCategory.create(id:153, at_grouped_category_id: 1 , order_key: 153  , at_category_id: '0425' , category_name1: '未分類' , category_name2 '避難所、避難場所')
Entities::AtTransactionCategory.create(id:154, at_grouped_category_id: 38, order_key: 1808 , at_category_id: '1681,1682,1686' , category_name1: '入金' , category_name2 '未分類')
Entities::AtTransactionCategory.create(id:155, at_grouped_category_id: 20, order_key: 1    , at_category_id: '0114,0117' , category_name1: '食費' , category_name2 '食費')
Entities::AtTransactionCategory.create(id:156, at_grouped_category_id: 20, order_key: 2    , at_category_id: '0116,0205,0210' , category_name1: '食費' , category_name2 '食料品')
Entities::AtTransactionCategory.create(id:157, at_grouped_category_id: 20, order_key: 3    , at_category_id: '0101,0102,0103,0104,0105,0106,0107,0108,0109,0111,0112,0113,0123,0127,0182' , category_name1: '食費' , category_name2 '外食')
Entities::AtTransactionCategory.create(id:158, at_grouped_category_id: 20, order_key: 4    , at_category_id: '' , category_name1: '食費' , category_name2 '朝ご飯')
Entities::AtTransactionCategory.create(id:159, at_grouped_category_id: 20, order_key: 5    , at_category_id: '0181' , category_name1: '食費' , category_name2 '昼ご飯')
Entities::AtTransactionCategory.create(id:160, at_grouped_category_id: 20, order_key: 6    , at_category_id: '' , category_name1: '食費' , category_name2 '夜ご飯')
Entities::AtTransactionCategory.create(id:161, at_grouped_category_id: 20, order_key: 7    , at_category_id: '0115,0118' , category_name1: '食費' , category_name2 'カフェ')
Entities::AtTransactionCategory.create(id:162, at_grouped_category_id: 20, order_key: 8    , at_category_id: '0128' , category_name1: '食費' , category_name2 'その他食費')
Entities::AtTransactionCategory.create(id:163, at_grouped_category_id: 21, order_key: 101  , at_category_id: '0202' , category_name1: '日用品' , category_name2 '日用品')
Entities::AtTransactionCategory.create(id:164, at_grouped_category_id: 21, order_key: 102  , at_category_id: '0207' , category_name1: '日用品' , category_name2 '生活雑貨')
Entities::AtTransactionCategory.create(id:165, at_grouped_category_id: 21, order_key: 103  , at_category_id: '' , category_name1: '日用品' , category_name2 '子ども関連')
Entities::AtTransactionCategory.create(id:166, at_grouped_category_id: 21, order_key: 104  , at_category_id: '0417' , category_name1: '日用品' , category_name2 'ペット関連')
Entities::AtTransactionCategory.create(id:167, at_grouped_category_id: 21, order_key: 105  , at_category_id: '' , category_name1: '日用品' , category_name2 'タバコ')
Entities::AtTransactionCategory.create(id:168, at_grouped_category_id: 21, order_key: 106  , at_category_id: '0201' , category_name1: '日用品' , category_name2 'その他日用品')
Entities::AtTransactionCategory.create(id:169, at_grouped_category_id: 22, order_key: 201  , at_category_id: '' , category_name1: '交通費' , category_name2 '交通費')
Entities::AtTransactionCategory.create(id:170, at_grouped_category_id: 22, order_key: 202  , at_category_id: '0381' , category_name1: '交通費' , category_name2 '電車')
Entities::AtTransactionCategory.create(id:171, at_grouped_category_id: 22, order_key: 203  , at_category_id: '0382' , category_name1: '交通費' , category_name2 'バス')
Entities::AtTransactionCategory.create(id:172, at_grouped_category_id: 22, order_key: 204  , at_category_id: '0383' , category_name1: '交通費' , category_name2 'タクシー')
Entities::AtTransactionCategory.create(id:173, at_grouped_category_id: 22, order_key: 205  , at_category_id: '0384' , category_name1: '交通費' , category_name2 '飛行機')
Entities::AtTransactionCategory.create(id:174, at_grouped_category_id: 22, order_key: 206  , at_category_id: '0306,0386,0399' , category_name1: '交通費' , category_name2 'その他交通')
Entities::AtTransactionCategory.create(id:175, at_grouped_category_id: 23, order_key: 301  , at_category_id: '0121,0124,0125,0126,0208,0302,0303,0308,0418' , category_name1: '趣味・娯楽' , category_name2 'レジャー・スポーツ')
Entities::AtTransactionCategory.create(id:176, at_grouped_category_id: 23, order_key: 302  , at_category_id: '' , category_name1: '趣味・娯楽' , category_name2 'イベント')
Entities::AtTransactionCategory.create(id:177, at_grouped_category_id: 23, order_key: 303  , at_category_id: '' , category_name1: '趣味・娯楽' , category_name2 '映画・動画')
Entities::AtTransactionCategory.create(id:178, at_grouped_category_id: 23, order_key: 304  , at_category_id: '0305' , category_name1: '趣味・娯楽' , category_name2 '音楽・ゲーム・漫画')
Entities::AtTransactionCategory.create(id:179, at_grouped_category_id: 23, order_key: 305  , at_category_id: '' , category_name1: '趣味・娯楽' , category_name2 '本')
Entities::AtTransactionCategory.create(id:180, at_grouped_category_id: 23, order_key: 306  , at_category_id: '0304,0307' , category_name1: '趣味・娯楽' , category_name2 '旅行')
Entities::AtTransactionCategory.create(id:181, at_grouped_category_id: 23, order_key: 307  , at_category_id: '0423,0424' , category_name1: '趣味・娯楽' , category_name2 'その他趣味・娯楽')
Entities::AtTransactionCategory.create(id:182, at_grouped_category_id: 24, order_key: 401  , at_category_id: '0204,0206,0209,0211' , category_name1: '衣服・美容' , category_name2 '衣服')
Entities::AtTransactionCategory.create(id:183, at_grouped_category_id: 24, order_key: 402  , at_category_id: '' , category_name1: '衣服・美容' , category_name2 'アクセサリー・小物')
Entities::AtTransactionCategory.create(id:184, at_grouped_category_id: 24, order_key: 403  , at_category_id: '' , category_name1: '衣服・美容' , category_name2 '下着')
Entities::AtTransactionCategory.create(id:185, at_grouped_category_id: 24, order_key: 404  , at_category_id: '' , category_name1: '衣服・美容' , category_name2 '美容院、理髪')
Entities::AtTransactionCategory.create(id:186, at_grouped_category_id: 24, order_key: 405  , at_category_id: '' , category_name1: '衣服・美容' , category_name2 '化粧品')
Entities::AtTransactionCategory.create(id:187, at_grouped_category_id: 24, order_key: 406  , at_category_id: '0419' , category_name1: '衣服・美容' , category_name2 'エステ・ネイル')
Entities::AtTransactionCategory.create(id:188, at_grouped_category_id: 24, order_key: 407  , at_category_id: '' , category_name1: '衣服・美容' , category_name2 'クリーニング')
Entities::AtTransactionCategory.create(id:189, at_grouped_category_id: 24, order_key: 408  , at_category_id: '' , category_name1: '衣服・美容' , category_name2 'その他衣服・美容')
Entities::AtTransactionCategory.create(id:190, at_grouped_category_id: 25, order_key: 501  , at_category_id: '' , category_name1: '交際費' , category_name2 '交際費')
Entities::AtTransactionCategory.create(id:191, at_grouped_category_id: 25, order_key: 502  , at_category_id: '0110,0119,0120,0122' , category_name1: '交際費' , category_name2 '飲み会')
Entities::AtTransactionCategory.create(id:192, at_grouped_category_id: 25, order_key: 503  , at_category_id: '0783,0784' , category_name1: '交際費' , category_name2 'プレゼント')
Entities::AtTransactionCategory.create(id:193, at_grouped_category_id: 25, order_key: 504  , at_category_id: '0414,0415' , category_name1: '交際費' , category_name2 '冠婚葬祭')
Entities::AtTransactionCategory.create(id:194, at_grouped_category_id: 25, order_key: 505  , at_category_id: '0799' , category_name1: '交際費' , category_name2 'その他交際費')
Entities::AtTransactionCategory.create(id:195, at_grouped_category_id: 26, order_key: 601  , at_category_id: '0301' , category_name1: '健康・医療' , category_name2 'フィットネス')
Entities::AtTransactionCategory.create(id:196, at_grouped_category_id: 26, order_key: 602  , at_category_id: '0403' , category_name1: '健康・医療' , category_name2 'マッサージ・整体')
Entities::AtTransactionCategory.create(id:197, at_grouped_category_id: 26, order_key: 603  , at_category_id: '0401' , category_name1: '健康・医療' , category_name2 '病院')
Entities::AtTransactionCategory.create(id:198, at_grouped_category_id: 26, order_key: 604  , at_category_id: '0402' , category_name1: '健康・医療' , category_name2 '薬代')
Entities::AtTransactionCategory.create(id:199, at_grouped_category_id: 26, order_key: 605  , at_category_id: '0404' , category_name1: '健康・医療' , category_name2 'その他健康・医療')
Entities::AtTransactionCategory.create(id:200, at_grouped_category_id: 27, order_key: 701  , at_category_id: '0903' , category_name1: '教育・教養' , category_name2 '書籍')
Entities::AtTransactionCategory.create(id:201, at_grouped_category_id: 27, order_key: 702  , at_category_id: '0904' , category_name1: '教育・教養' , category_name2 '新聞・雑誌')
Entities::AtTransactionCategory.create(id:202, at_grouped_category_id: 27, order_key: 703  , at_category_id: '0405' , category_name1: '教育・教養' , category_name2 '習いごと')
Entities::AtTransactionCategory.create(id:203, at_grouped_category_id: 27, order_key: 704  , at_category_id: '0902' , category_name1: '教育・教養' , category_name2 '教科書・参考書')
Entities::AtTransactionCategory.create(id:204, at_grouped_category_id: 27, order_key: 705  , at_category_id: '0406,0407,0408' , category_name1: '教育・教養' , category_name2 '学費')
Entities::AtTransactionCategory.create(id:205, at_grouped_category_id: 27, order_key: 706  , at_category_id: '0906' , category_name1: '教育・教養' , category_name2 '塾')
Entities::AtTransactionCategory.create(id:206, at_grouped_category_id: 27, order_key: 707  , at_category_id: '0999' , category_name1: '教育・教養' , category_name2 'その他教育・教養')
Entities::AtTransactionCategory.create(id:207, at_grouped_category_id: 28, order_key: 801  , at_category_id: '1781' , category_name1: '現金・カード' , category_name2 'ATM引き出し')
Entities::AtTransactionCategory.create(id:208, at_grouped_category_id: 28, order_key: 802  , at_category_id: '' , category_name1: '現金・カード' , category_name2 'カード引き落とし')
Entities::AtTransactionCategory.create(id:209, at_grouped_category_id: 28, order_key: 803  , at_category_id: '' , category_name1: '現金・カード' , category_name2 '電子マネーにチャージ')
Entities::AtTransactionCategory.create(id:210, at_grouped_category_id: 28, order_key: 804  , at_category_id: '1581' , category_name1: '現金・カード' , category_name2 'カード返済')
Entities::AtTransactionCategory.create(id:211, at_grouped_category_id: 28, order_key: 805  , at_category_id: '1782,1783,1784,1785,1786,1787,1799' , category_name1: '現金・カード' , category_name2 'その他現金・カード')
Entities::AtTransactionCategory.create(id:212, at_grouped_category_id: 29, order_key: 901  , at_category_id: '' , category_name1: '水道・光熱費' , category_name2 '光熱費')
Entities::AtTransactionCategory.create(id:213, at_grouped_category_id: 29, order_key: 902  , at_category_id: '0581' , category_name1: '水道・光熱費' , category_name2 '電気代')
Entities::AtTransactionCategory.create(id:214, at_grouped_category_id: 29, order_key: 903  , at_category_id: '0582' , category_name1: '水道・光熱費' , category_name2 '水道代')
Entities::AtTransactionCategory.create(id:215, at_grouped_category_id: 29, order_key: 904  , at_category_id: '0583' , category_name1: '水道・光熱費' , category_name2 'ガス・灯油代')
Entities::AtTransactionCategory.create(id:216, at_grouped_category_id: 29, order_key: 905  , at_category_id: '0599' , category_name1: '水道・光熱費' , category_name2 'その他水道・光熱費')
Entities::AtTransactionCategory.create(id:217, at_grouped_category_id: 30, order_key: 1001 , at_category_id: '0681' , category_name1: '通信費' , category_name2 '携帯電話')
Entities::AtTransactionCategory.create(id:218, at_grouped_category_id: 30, order_key: 1002 , at_category_id: '0682' , category_name1: '通信費' , category_name2 '固定電話')
Entities::AtTransactionCategory.create(id:219, at_grouped_category_id: 30, order_key: 1003 , at_category_id: '0684' , category_name1: '通信費' , category_name2 'インターネット')
Entities::AtTransactionCategory.create(id:220, at_grouped_category_id: 30, order_key: 1004 , at_category_id: '0685' , category_name1: '通信費' , category_name2 '放送視聴料')
Entities::AtTransactionCategory.create(id:221, at_grouped_category_id: 30, order_key: 1005 , at_category_id: '0412' , category_name1: '通信費' , category_name2 '情報サービス')
Entities::AtTransactionCategory.create(id:222, at_grouped_category_id: 30, order_key: 1006 , at_category_id: '0411' , category_name1: '通信費' , category_name2 '宅配便・運送')
Entities::AtTransactionCategory.create(id:223, at_grouped_category_id: 30, order_key: 1007 , at_category_id: '0699' , category_name1: '通信費' , category_name2 'その他通信費')
Entities::AtTransactionCategory.create(id:224, at_grouped_category_id: 31, order_key: 1101 , at_category_id: '0409' , category_name1: '住宅' , category_name2 '家賃')
Entities::AtTransactionCategory.create(id:225, at_grouped_category_id: 31, order_key: 1102 , at_category_id: '' , category_name1: '住宅' , category_name2 '住宅ローン')
Entities::AtTransactionCategory.create(id:226, at_grouped_category_id: 31, order_key: 1103 , at_category_id: '' , category_name1: '住宅' , category_name2 '管理費・積立金')
Entities::AtTransactionCategory.create(id:227, at_grouped_category_id: 31, order_key: 1104 , at_category_id: '' , category_name1: '住宅' , category_name2 '家具')
Entities::AtTransactionCategory.create(id:228, at_grouped_category_id: 31, order_key: 1105 , at_category_id: '0203' , category_name1: '住宅' , category_name2 '家電')
Entities::AtTransactionCategory.create(id:229, at_grouped_category_id: 31, order_key: 1106 , at_category_id: '' , category_name1: '住宅' , category_name2 'リフォーム')
Entities::AtTransactionCategory.create(id:230, at_grouped_category_id: 31, order_key: 1107 , at_category_id: '0483' , category_name1: '住宅' , category_name2 '地震・火災保険')
Entities::AtTransactionCategory.create(id:231, at_grouped_category_id: 31, order_key: 1108 , at_category_id: '0410,0482,0484' , category_name1: '住宅' , category_name2 'その他住宅')
Entities::AtTransactionCategory.create(id:232, at_grouped_category_id: 32, order_key: 1201 , at_category_id: '' , category_name1: '車・バイク' , category_name2 'ガソリン')
Entities::AtTransactionCategory.create(id:233, at_grouped_category_id: 32, order_key: 1202 , at_category_id: '1282' , category_name1: '車・バイク' , category_name2 '駐車場')
Entities::AtTransactionCategory.create(id:234, at_grouped_category_id: 32, order_key: 1203 , at_category_id: '1284' , category_name1: '車・バイク' , category_name2 '道路料金')
Entities::AtTransactionCategory.create(id:235, at_grouped_category_id: 32, order_key: 1204 , at_category_id: '1288' , category_name1: '車・バイク' , category_name2 '自動車ローン')
Entities::AtTransactionCategory.create(id:236, at_grouped_category_id: 32, order_key: 1205 , at_category_id: '1283' , category_name1: '車・バイク' , category_name2 '自動車保険')
Entities::AtTransactionCategory.create(id:237, at_grouped_category_id: 32, order_key: 1206 , at_category_id: '1285' , category_name1: '車・バイク' , category_name2 '自動車税')
Entities::AtTransactionCategory.create(id:238, at_grouped_category_id: 32, order_key: 1207 , at_category_id: '1286,1287' , category_name1: '車・バイク' , category_name2 '車検・整備')
Entities::AtTransactionCategory.create(id:239, at_grouped_category_id: 32, order_key: 1208 , at_category_id: '0413,1289,1299' , category_name1: '車・バイク' , category_name2 'その他車・バイク')
Entities::AtTransactionCategory.create(id:240, at_grouped_category_id: 33, order_key: 1301 , at_category_id: '1101' , category_name1: '税・社会保障' , category_name2  '所得税・住民税')
Entities::AtTransactionCategory.create(id:241, at_grouped_category_id: 33, order_key: 1302 , at_category_id: '1004' , category_name1: '税・社会保障' , category_name2  '年金')
Entities::AtTransactionCategory.create(id:242, at_grouped_category_id: 33, order_key: 1303 , at_category_id: '' , category_name1: '税・社会保障' , category_name2  '健康保険')
Entities::AtTransactionCategory.create(id:243, at_grouped_category_id: 33, order_key: 1304 , at_category_id: '0416,1099,1102,1182,1199' , category_name1: '税・社会保障' , category_name2  'その他税・社会保障')
Entities::AtTransactionCategory.create(id:244, at_grouped_category_id: 34, order_key: 1401 , at_category_id: '' , category_name1: '保険' , category_name2 '保険')
Entities::AtTransactionCategory.create(id:245, at_grouped_category_id: 34, order_key: 1402 , at_category_id: '1002' , category_name1: '保険' , category_name2 '生命保険')
Entities::AtTransactionCategory.create(id:246, at_grouped_category_id: 34, order_key: 1403 , at_category_id: '1003' , category_name1: '保険' , category_name2 '医療保険')
Entities::AtTransactionCategory.create(id:247, at_grouped_category_id: 34, order_key: 1404 , at_category_id: '' , category_name1: '保険' , category_name2 'その他保険')
Entities::AtTransactionCategory.create(id:248, at_grouped_category_id: 35, order_key: 1501 , at_category_id: '' , category_name1: '特別な支出' , category_name2 '特別な支出')
Entities::AtTransactionCategory.create(id:249, at_grouped_category_id: 35, order_key: 1502 , at_category_id: '' , category_name1: '特別な支出' , category_name2 '家具・家電')
Entities::AtTransactionCategory.create(id:250, at_grouped_category_id: 35, order_key: 1503 , at_category_id: '' , category_name1: '特別な支出' , category_name2 '住宅・リフォーム')
Entities::AtTransactionCategory.create(id:251, at_grouped_category_id: 35, order_key: 1504 , at_category_id: '' , category_name1: '特別な支出' , category_name2 '結婚')
Entities::AtTransactionCategory.create(id:252, at_grouped_category_id: 35, order_key: 1505 , at_category_id: '' , category_name1: '特別な支出' , category_name2 '妊活・出産')
Entities::AtTransactionCategory.create(id:253, at_grouped_category_id: 35, order_key: 1506 , at_category_id: '' , category_name1: '特別な支出' , category_name2 '介護')
Entities::AtTransactionCategory.create(id:254, at_grouped_category_id: 35, order_key: 1507 , at_category_id: '' , category_name1: '特別な支出' , category_name2 'その他特別な出費')
Entities::AtTransactionCategory.create(id:255, at_grouped_category_id: 36, order_key: 1601 , at_category_id: '' , category_name1: 'その他' , category_name2  '立替金')
Entities::AtTransactionCategory.create(id:256, at_grouped_category_id: 36, order_key: 1602 , at_category_id: '' , category_name1: 'その他' , category_name2  '仕送り')
Entities::AtTransactionCategory.create(id:257, at_grouped_category_id: 36, order_key: 1603 , at_category_id: '' , category_name1: 'その他' , category_name2  'おこづかい')
Entities::AtTransactionCategory.create(id:258, at_grouped_category_id: 36, order_key: 1604 , at_category_id: '1481,1482,1483,1499,1881' , category_name1: 'その他' , category_name2  '事業費')
Entities::AtTransactionCategory.create(id:259, at_grouped_category_id: 36, order_key: 1605 , at_category_id: '1582,1599' , category_name1: 'その他' , category_name2  '返済')
Entities::AtTransactionCategory.create(id:260, at_grouped_category_id: 36, order_key: 1606 , at_category_id: '1882,1883,1884,1885,1899' , category_name1: 'その他' , category_name2  '雑費')
Entities::AtTransactionCategory.create(id:261, at_grouped_category_id: 36, order_key: 1607 , at_category_id: '' , category_name1: 'その他' , category_name2  '使途不明金')
Entities::AtTransactionCategory.create(id:262, at_grouped_category_id: 36, order_key: 1608 , at_category_id: '0420,0421,0422,0425,1084' , category_name1: 'その他' , category_name2  'その他')
Entities::AtTransactionCategory.create(id:263, at_grouped_category_id: 37, order_key: 1701 , at_category_id: '0000' , category_name1: '未分類' , category_name2  '未分類')
Entities::AtTransactionCategory.create(id:264, at_grouped_category_id: 38, order_key: 1801 , at_category_id: '1684' , category_name1: '入金' , category_name2 '給与')
Entities::AtTransactionCategory.create(id:265, at_grouped_category_id: 38, order_key: 1802 , at_category_id: '1685' , category_name1: '入金' , category_name2 '賞与')
Entities::AtTransactionCategory.create(id:266, at_grouped_category_id: 38, order_key: 1803 , at_category_id: '1683' , category_name1: '入金' , category_name2 '立替金返済')
Entities::AtTransactionCategory.create(id:267, at_grouped_category_id: 38, order_key: 1804 , at_category_id: '' , category_name1: '入金' , category_name2 '臨時収入')
Entities::AtTransactionCategory.create(id:268, at_grouped_category_id: 38, order_key: 1805 , at_category_id: '' , category_name1: '入金' , category_name2 '事業・副業')
Entities::AtTransactionCategory.create(id:269, at_grouped_category_id: 38, order_key: 1806 , at_category_id: '1687,1690,1691' , category_name1: '入金' , category_name2 '配当・不動産所得')
Entities::AtTransactionCategory.create(id:270, at_grouped_category_id: 38, order_key: 1807 , at_category_id: '1688,1689,1692,1699' , category_name1: '入金' , category_name2 'その他入金')

# UserCancelQuestioin
Entities::UserCancelQuestion.create(id:1, cancel_reason: '金融機関の登録が難しかった')
Entities::UserCancelQuestion.create(id:2, cancel_reason: 'セキュリティの懸念があった')
Entities::UserCancelQuestion.create(id:3, cancel_reason: '他サービスの方が便利に感じた')
Entities::UserCancelQuestion.create(id:4, cancel_reason: '使いこなせなかった')
Entities::UserCancelQuestion.create(id:5, cancel_reason: 'あまり使わなかった')
Entities::UserCancelQuestion.create(id:6, cancel_reason: 'その他')
